### ISSUE TITLE
No such file or directory error during installation

### ISSUE THREAD

**Issue by steve1607** [Dani3lSun/docker-db-apex-dev#1]
Hi Daniel,
I downloaded all files and put the images into the "files" folder. The installation could not be finished successful due to an error that was thrown. Did I make a mistake or do you know where the error comes from?

Best regards,
Steven

![screenshot 148](https://cloud.githubusercontent.com/assets/9033420/25983842/837cb6f6-36e7-11e7-935d-c8104eaa5d44.png)

**Comment by Dani3lSun** [comment]
Hi @steve1607 

I can´t see the files that are already in the Github Repo.
https://github.com/Dani3lSun/docker-db-apex-dev/tree/master/files
So I think these are missing in your local filesystem!

**Comment by steve1607** [comment]
Oh that was not very clever. I deleted them by mistake. 

But regardless of that, The error message still stays the same after I added the files back where they belong to.


![screenshot 150](https://cloud.githubusercontent.com/assets/9033420/26009616/e4e3fe74-3749-11e7-8d16-bed5d038f01c.png)

**Comment by Dani3lSun** [comment]
Hmm OK confusing...seems that it has problems with your Character Return Settings...Normally all Scripts have LF instead of the Windows one (CRLF). That should be good for Docker, because it actually runs a Linux inside...Have you edited a file with an Windows editor?

**Comment by steve1607** [comment]
No, I never did. 

I just deleted all files and cloned them again and the error message remains the same.

**Comment by Dani3lSun** [comment]
Ok I tested in on Linux and MacOS Host, unfortunately not on Windows Hosts because I do not have one...
It seems that your Docker Installation has Problems with the Bash..."/bin/bash" is missing.
Can you try to replace all
```
#!/bin/bash
```
with
```
#!/bin/sh
```
In every *.sh file in the scripts subdirectory (Usually it´s in the first line, telling the terminal which shell should be used).

**Comment by steve1607** [comment]
Okay, I understand. I will check that next week. 
Have a nice weekend and thanks for your quick responses!

**Comment by steve1607** [comment]
![screenshot 151](https://cloud.githubusercontent.com/assets/9033420/26117988/955ff2a0-3a68-11e7-8195-92795b912e66.png)

I tried as you said but it does not seem to change very much. Strange issue.

**Comment by Dani3lSun** [comment]
is this issue still relevant? If not, I will close the issue...

**Comment by Dani3lSun** [comment]
Just for your interest, it seems that windows git sometimes converts linux line endings to windows ones:
https://forums.docker.com/t/error-while-running-docker-code-in-powershell/34059/5
