### ISSUE TITLE
Connection to database not possible and no apex running

### ISSUE THREAD

**Issue by sebastianreinig** [Dani3lSun/docker-db-apex-dev#11]
Hi,

I have issues with the current release.

I cant get access to the database:
"Status: Nicht erfolgreich -Test nicht erfolgreich: I/O-Fehler: Got minus one from a read call, connect lapse 72 ms., Authentication lapse 0 ms."

And the tomcat ist giving a 404 when accessing apex.

Here is a screenshot of the processes running as oracle user.
![image](https://user-images.githubusercontent.com/18229650/40992854-391d622e-68f8-11e8-9533-344aedc6303a.png)

Do you have an idea whats wrong?

Btw. its a very nice docker build ;) The version before apex 18 was great. Now I wanted to use it again.

**Comment by Dani3lSun** [comment]
Hi @sebastianreinig 
do you use the newest scripts from this repository?
Seems that something went wrong when building the image...
For me it works here on my Mac quite fine, just have a detailed look at the console output when building the image

**Comment by Dani3lSun** [comment]
Ah ok, good to know! Great that it works now!
