### ISSUE TITLE
APEX Web Source not working

### ISSUE THREAD

**Issue by eferreira07** [Dani3lSun/docker-db-apex-dev#16]
I've been trying to configure APEX Web Source with this VM setup without success. Even create a new wallet and resent the wallet it is still showing ORA-29024: Certificate validation failure while trying to configure web source in Apex. 

Have you had any luck on using web source locally?

**Comment by hairpin666** [comment]
https://blogs.oracle.com/apex/apex-https-certificates-and-the-oracle-wallet
This worked for me, just make sure to follow the instructions.

**Comment by Dani3lSun** [comment]
I think this issue has nothing to do with this docker image, it is more an Oracle wallet thing...
As a rule of thumb: Use the CA certificates (in Oracle wallet) if DB version >= 12, for older releases the site certificate is enough...
