### ISSUE TITLE
Password policies, ! character not accepted in Oracle ORDS

### ISSUE THREAD

**Issue by yevon** [Dani3lSun/docker-db-apex-dev#17]
Its seems that if you put the "!" simbol at the end of your password, the ords config fails, and it is unable to connect to the database. It would be nice to advertise this on the docs. Once I corrected this, I could connect without problems.

**Comment by Dani3lSun** [comment]
This is more an ORDS thing and not so much specific to this docker image...The exclamation mark has a special meaning for ORDS password encryption...
