### ISSUE TITLE
It would be awesome if you could do install scripts for oracle express edition as well!

### ISSUE THREAD

**Issue by VanadiumJade** [Dani3lSun/docker-db-apex-dev#18]
So I absolutely love your pre-built build scripts - I would love if you could add an option for Oracle database express edition!

Happy to buy you a coffee or two to fuel your mad scripting skills 🥇 

Van.

**Comment by Dani3lSun** [comment]
Hi @VanadiumJade 
it is in the making! I already created the installation script here on dev, but it's not finished yet...Just check the github repo the upcoming weeks, I hope it is done soon! :)

**Comment by vatasi** [comment]
I have a task to extend our Docker template with the XE edition - so before I start to reinvent a wheel probably I could learn something from you, even from DEV scripts. So I could be your beta-tester :)

**Comment by VanadiumJade** [comment]
Hows this coming along? keen for XE :)

**Comment by Dani3lSun** [comment]
I decided to not include XE installation, thus the whole installation process is very different to the normale EE installation...Therefore I just added 19.3 EE installation...
This also has the benefit of having all EE features with no limitation + be on the bleeding edge (thus EE release always comes earlier than XE builds)

**Comment by zhouhao27** [comment]
Is 19.3 EE free to use? Thanks.

**Comment by Dani3lSun** [comment]
I'm not an Oracle licensing pro, but for my understanding it is "free" to use for development purposes, if you apply to the OTN Development license (when you download software from OTN, you already applied to it)...But it's limited, see:
https://www.jobacle.nl/?p=1508
But if you install it on your local machine, and do local development with it (which is btw the main purpose of this docker image) you should be save...
