### ISSUE TITLE
Make database persistent

### ISSUE THREAD

**Issue by hairpin666** [Dani3lSun/docker-db-apex-dev#19]
How do we have to map the volumes to keep the database data persistent? Once the conainer is stopped all data is lost. Is there an easy way?

**Comment by Dani3lSun** [comment]
It is persistent, just use the docker run command once, just for creating the container, command is in the readme (part 5 of installation).
After that use docker start/stop <your-container>

**Comment by hairpin666** [comment]
Thanks, it works now I guess i used the wrong command.
Thanks so much for publishing this image!
