### ISSUE TITLE
sqlplus - no listener

### ISSUE THREAD

**Issue by cyryl1972** [Dani3lSun/docker-db-apex-dev#24]
Hello, 
I have the following when I am trying to connect to the database: 

PS D:\> sqlplus system/oracle@//localhost:1521/orcl
SQL*Plus: Release 12.2.0.1.0 Production on Wed Jun 12 09:19:22 2019
Copyright (c) 1982, 2016, Oracle.  All rights reserved.
ERROR:
ORA-12541: TNS:no listener

PS D:\> sqlplus system/oracle@localhost/orcl
SQL*Plus: Release 12.2.0.1.0 Production on Wed Jun 12 09:19:36 2019
Copyright (c) 1982, 2016, Oracle.  All rights reserved.
ERROR:
ORA-12541: TNS:no listener 

Container is started as you did in the readme file.

PS: I also tried by replacing localhost by 0.0.0.0 or 127.0.0.1. 
Thanks for your help, 
Cyryl

**Comment by Dani3lSun** [comment]
Hi @cyryl1972 
indeed you are correct, sqlplus gaves me the same error, when I use SQLcl it works...
```
sql system/oracle@localhost:1521/orcl
```
This is strange, thus both tools should use the same connection string settings...Nevertheless I usually create an entry in my local tnsnames.ora, and this works for both pretty well:
```
orcl_docker =
  (description =
    (address_list =
      (address = (protocol = tcp)(host = 127.0.0.1)(port = 1521))
    )
    (connect_data =
      (server = dedicated)
      (service_name = orcl)
    )
  )
```

**Comment by cyryl1972** [comment]
Hello @Dani3lSun,

Thanks for this quick-like-hell answer ;-) 

it is working adding **--privileged** flag. 
I have also restarted docker process (I am using Docker Desktop on Windows host). 

This issue is closed. 

have a good day,
Cyryl

**Comment by Dani3lSun** [comment]
That's confusing that the flag *--privileged* has an impact on this...It is more insecure if you use this on a container, thus it has more rights, but for development on localhost it should be fine...
I tried the following connection string, and this also works with sqlplus:
```
sqlplus system/oracle@'(description=(address_list=(address=(protocol=tcp)(host=127.0.0.1)(port=1521)))(connect_data=(server=dedicated)(service_name=orcl)))'
```

**Comment by cyryl1972** [comment]
@Dani3lSun

**Comment by Dani3lSun** [comment]
Maybe it's a thing between OCI (sqlplus) and JDBC Thin Client (SQLcl), but for my understanding both just use TCP/IP...I will close this issue now, thus it works now for you! :)

**Comment by cyryl1972** [comment]
It is strange. I am at all a docker expert ... so maybe I don't understand all the things. 

I did another test: 
1. restart docker process
2. run container without --privileged flag 
3. sqlplus is working fine !!

so sorry for bothering you for a non-existent issue.
