### ISSUE TITLE
/bin/sh: /scripts/install_main.sh: /bin/bash^M: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by eferreira07** [Dani3lSun/docker-db-apex-dev#25]
Trying to create a docker img and I'm seeing the following error:

Step 6/9 : RUN /scripts/install_main.sh
 ---> Running in 3316a0871e7d
/bin/sh: /scripts/install_main.sh: /bin/bash^M: bad interpreter: No such file or directory

Any idea of what it might be?

Thank you in advance.

**Comment by Dani3lSun** [comment]
Are you on windows? And if so, have you cloned the git repo or downloaded the repository zip file?
It seems that the windows git client does replace line endings to windows ones (LF vs CRLF)...

https://github.com/Dani3lSun/docker-db-apex-dev/issues/1#issuecomment-392760739

Just download the zip and you should be fine...

**Comment by eferreira07** [comment]
First of thanks for sharing this useful github.
You're right and I got it installed already.
