### ISSUE TITLE
Java not found

### ISSUE THREAD

**Issue by scottcourtney** [Dani3lSun/docker-db-apex-dev#27]
I am attempting to build the image and receiving: 
Validations.......................................
......Checking Scripts......
......Checking Files......
......Checking Downloaded Files......
Java not found!
The command '/bin/sh -c /scripts/install_main.sh' returned a non-zero code: 1

I have within the Dockerfile JAVA_HOME=/Library/Java

**Comment by Dani3lSun** [comment]
Did you download all the needed software as listed in the readme?
https://github.com/Dani3lSun/docker-db-apex-dev#installation
If just Java is missing, the link "AdoptOpenJDK 11.0.5+10 - Linux x64 tar.gz" would be important...
Download all the stuff and put it into the "files" folder...

**Comment by scottcourtney** [comment]
Yes I have AdoptOpenJDK downloaded and everything placed within the files folder

<img width="385" alt="Screen Shot 2019-12-17 at 5 01 44 PM" src="https://user-images.githubusercontent.com/7663121/71038153-35cb2600-20ef-11ea-8290-4695a2a7efcd.png">

**Comment by Dani3lSun** [comment]
I see you downloaded it, but you also unzipped all the installation files...The docker build scripts expect the files not the unzipped folders...
I guess you downloaded it with Safari, which opens files by default after downloading...
<img width="772" alt="General_and_Favorites" src="https://user-images.githubusercontent.com/698942/71038364-f833c080-2121-11ea-997e-230900dabffd.png">

And btw. I don't recommend changing paths in the dockerfile (e.g. JAVA_HOME), thus a RedHat based linux does not have a /Library path for example...Just let all path specific settings in it's default...

**Comment by Dani3lSun** [comment]
It should look like this:
<img width="425" alt="Screen Shot 2019-12-17 at 23 12 24" src="https://user-images.githubusercontent.com/698942/71038725-c3743900-2122-11ea-9c6b-1015e239730e.png">

**Comment by scottcourtney** [comment]
That worked by not unzipping them. Thanks
