### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by omarsawalhah** [Dani3lSun/docker-db-apex-dev#3]
Hi, 
I followed all the instructions, but I got this error while creating the database.

Checking Temp space: must be greater than 500 MB.   Actual 4095 MB    Passed
Checking swap space: must be greater than 150 MB.   Actual 1022 MB    Passed
Preparing to launch Oracle Universal Installer from /tmp/OraInstall2017-08-16_10-44-17AM. Please wait ...**[FATAL] [INS-32021] Installer has detected that the available disk space on the volume for Oracle home (/u01/app/oracle/product/12.2.0.1/dbhome) is insufficient.**
   ACTION: Choose a location for Oracle home that has enough space (minimum of 7,680MB) or free up space on the existing volume.
A log of this session is currently saved as: /tmp/OraInstall2017-08-16_10-44-17AM/installActions2017-08-16_10-44-17AM.log. Oracle recommends that if you want to keep this log, you should move it from the temporary location.
running Oracle root scripts...
Creating database. SID: db12c
mv: cannot stat '/u01/app/oracle-product/12.2.0.1/dbhome/dbs': No such file or directory
ln: failed to create symbolic link '/u01/app/oracle-product/12.2.0.1/dbhome/dbs': No such file or directory
bash: /u01/app/oracle/product/12.2.0.1/dbhome/bin/lsnrctl: No such file or directory
bash: /u01/app/oracle/product/12.2.0.1/dbhome/bin/dbca: No such file or directory
bash: /u01/app/oracle/product/12.2.0.1/dbhome/bin/sqlplus: No such file or directory

**Comment by Dani3lSun** [comment]
Seems that you ran out of available disk space on your machine...For the build this images needs at least 40GB of free space. After the build has finished the whole image should have a size around 15GB...

You normally can check your disk space with:

```
docker info
```

**Comment by omarsawalhah** [comment]
Thanks, 
I think you have to mention this in the README.md or any other place.
Omar

**Comment by omarsawalhah** [comment]
Hi-
<img width="823" alt="screen shot 2017-08-16 at 2 44 49 pm" src="https://user-images.githubusercontent.com/2116277/29361716-8203b130-8291-11e7-91a3-6131ab6f2c93.png">
I tried after I freed 53GB, and deleted  the failed image, but the same problem persist.

   ACTION: Choose a location for Oracle home that has enough space (minimum of 7,680MB) or free up space on the existing volume.
A log of this session is currently saved as: /tmp/OraInstall2017-08-16_09-58-48AM/installActions2017-08-16_09-58-48AM.log. Oracle recommends that if you want to keep this log, you should move it from the temporary location.
running Oracle root scripts...
Creating database. SID: db12c
mv: cannot stat '/u01/app/oracle-product/12.2.0.1/dbhome/dbs': No such file or directory
ln: failed to create symbolic link '/u01/app/oracle-product/12.2.0.1/dbhome/dbs': No such file or directory
bash: /u01/app/oracle/product/12.2.0.1/dbhome/bin/lsnrctl: No such file or directory
bash: /u01/app/oracle/product/12.2.0.1/dbhome/bin/dbca: No such file or directory
Configure listener.
bash: /u01/app/oracle/product/12.2.0.1/dbhome/bin/sqlplus: No such file or directory
bash: /u01/app/oracle/product/12.2.0.1/dbhome/bin/lsnrctl: No such file or directory
bash: /u01/app/oracle/product/12.2.0.1/dbhome/bin/lsnrctl: No such file or directory
bash: /u01/app/oracle/product/12.2.0.1/dbhome/bin/sqlplus: No such file or directory

For the default VM I have 19GB for the VMDK file, does this affect the image building or what?

Regards
Omar

**Comment by Dani3lSun** [comment]
Do you build the images on your mac or in a virtual machine?
If you build it directly on the mac (I would do so) you have to consider that all docker stuff is inside an disk image (because docker runs only native on linux, it is necessary to run a little docker vm on the mac that uses this image file).

This image file can´t exceed 64GB, it is located here:

```
~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2
```

If you already have other docker images or failed builds that uses space, than it could be that this image file is full.

More information about that file:

```
/Applications/Docker.app/Contents/MacOS/qemu-img info ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2
```
If it is full you can delete containers and images like:
```
# show all containers
docker ps -a
# delete container
docker rm <container-id>
# show all images
docker images
# delete image
docker rmi <image-name>
```
If you would like to extend you image file "Docker.qcow2", here´s a good how-to:
https://gist.github.com/stefanfoulis/5bd226b25fa0d4baedc4803fc002829e
(It is not that easy ^^)

**Comment by Dani3lSun** [comment]
I added a file size hint to the readme...
