### ISSUE TITLE
sqldeveloper web

### ISSUE THREAD

**Issue by vdkstefaan** [Dani3lSun/docker-db-apex-dev#33]
when I go to the sql-developer link and try to login, I get this error after entering the username and clicking on Next:
The request could not be mapped to any database. Check the request URL is correct, and that URL to database mappings have been correctly configured

**Comment by Dani3lSun** [comment]
Which credentials do you use?
Can you share a screen shot of the login page and the error page?
Thanks...

**Comment by vdkstefaan** [comment]
![Screenshot 2020-05-04 at 15 49 21](https://user-images.githubusercontent.com/5338232/80972896-f80d3680-8e1e-11ea-8909-958d31e37b07.png)
![Screenshot 2020-05-04 at 15 49 33](https://user-images.githubusercontent.com/5338232/80972901-f9d6fa00-8e1e-11ea-93de-13a36af39982.png)
![Screenshot 2020-05-04 at 15 49 51](https://user-images.githubusercontent.com/5338232/80972905-fba0bd80-8e1e-11ea-9c47-e7b424f561ee.png)

**Comment by Dani3lSun** [comment]
Hmm seems correct...Did you get any errors during image installation (console output)?
Does the DB schema "SDW_ADMIN" exist in the target DB?

**Comment by vdkstefaan** [comment]
no I don't have a SDW_ADMIN schema

**Comment by Dani3lSun** [comment]
Then I guess there was some error during installation...Or you used an old script etc...
The ORDS installation script should contain this function:
https://github.com/Dani3lSun/docker-db-apex-dev/blob/493a232f3d945f2e1b7748fc2293bd68a19a37c7/scripts/install_ords.sh#L4
I would download the latest zip file from this repo again, put the needed files into "files" folder and then try to build the Docker image again...

**Comment by vdkstefaan** [comment]
I run the code again within the block and now it's working so something went wrong during the install...

**Comment by Dani3lSun** [comment]
Perfect, good to hear!
