### ISSUE TITLE
Oracle Database Timezone

### ISSUE THREAD

**Issue by wheeliea937** [Dani3lSun/docker-db-apex-dev#39]
I would like to modify the database timezone to be 'America/New_York'.  So I altered the database and set the new timezone:

alter database set time_zone = 'America/New_York';

I then selected sysdate from dual and got the local time.

I bounced the docker container, and the database timezone is set back to UTC.

I am assuming that there are scripts that are setting these time zones on container startup, how can I alter the time zones to EST?

Thanks,
Beth Wheeling

**Comment by Dani3lSun** [comment]
This is shown in the readme...The Dockerfile contains a env variable called `TIME_ZONE `, so just set this and build the image again.
