### ISSUE TITLE
Pipe (|) in URL

### ISSUE THREAD

**Issue by mgoricki** [Dani3lSun/docker-db-apex-dev#5]
I think there's an issue with Tomcat configuration. It breaks on URLs that contain pipe (|). It's easy to reproduce - go to the APEX Builder and click on any of the Top Apps links (in my case IG Cookbook):
![image](https://user-images.githubusercontent.com/3269338/31048923-07aef7b2-a629-11e7-8f21-42512721a740.png)

**Comment by Dani3lSun** [comment]
Hey @mgoricki 
unfortunately this seems to be an Tomcat issue.
At some version (8.0.39) they added more strict parsing of URLs. So some characters are not allowed any more...
See:
https://stackoverflow.com/questions/41053653/tomcat-8-is-not-able-to-handle-get-request-with-in-query-parameters
https://stackoverflow.com/questions/42340207/how-to-make-apache-tomcat-8-0-41-to-allow-the-pipe-character-in-url-get-request
https://bz.apache.org/bugzilla/show_bug.cgi?id=60425
I too saw this error a couple of months ago, so we at FOEX implemented an fix into the FDA (Browser Extension), this cuts out pipe characters from URLs...
