### ISSUE TITLE
Connection to APEX via localhost:8080/ords

### ISSUE THREAD

**Issue by PhilippeKayser** [Dani3lSun/docker-db-apex-dev#7]
Hi,
I ran into an issue I'm not sure how to solve myself. After building the docker image and then running it, I am not able to access APEX via the provided link localhost:8080/ords. The response I get by trying to access it is ERR_EMPTY_RESPONSE. For the rest, everything works, ssh, oracle database etc... Any idea what could have gone wrong in the ords or APEX? (Great container though)

**Comment by Dani3lSun** [comment]
Hey @PhilippeKayser 

sorry for the late response...Completely missed to come back to you...

Is this issue still a problem for you? Or have you solved it meanwhile?

**Comment by PhilippeKayser** [comment]
Hey @Dani3lSun,
I'm sorry, I could have logged my progress on this as it actually resolved itself. I found out that APEX had not been installed correctly, due to a corrupted download of the compressed file. Couldn't find a reason why this was the case. A redownload solved the problem and all works well now.

**Comment by Dani3lSun** [comment]
Ok great to hear that it works now for you! I will close this issue...
