### ISSUE TITLE
Running docker container

### ISSUE THREAD

**Issue by KristjanVall** [Dani3lSun/docker-db-apex-dev#9]
`setenforce: SELinux is disabled
Creating tnsnames.ora
/scripts/setenv.sh: line 23: /u01/app/oracle/product/12.2.0.1/dbhome/network/admin/tnsnames.ora: No such file or directory
/scripts/setenv.sh: line 31: /u01/app/oracle/product/12.2.0.1/dbhome/network/admin/listener.ora: No such file or directory
/scripts/setenv.sh: line 32: /u01/app/oracle/product/12.2.0.1/dbhome/network/admin/listener.ora: No such file or directory
/scripts/setenv.sh: line 33: /u01/app/oracle/product/12.2.0.1/dbhome/network/admin/listener.ora: No such file or directory
/scripts/setenv.sh: line 34: /u01/app/oracle/product/12.2.0.1/dbhome/network/admin/listener.ora: No such file or directory
/scripts/setenv.sh: line 35: /u01/app/oracle/product/12.2.0.1/dbhome/network/admin/listener.ora: No such file or directory
/scripts/setenv.sh: line 36: /u01/app/oracle/product/12.2.0.1/dbhome/network/admin/listener.ora: No such file or directory
/scripts/setenv.sh: line 37: /u01/app/oracle/product/12.2.0.1/dbhome/network/admin/listener.ora: No such file or directory
/scripts/setenv.sh: line 38: /u01/app/oracle/product/12.2.0.1/dbhome/network/admin/listener.ora: No such file or directory
/scripts/setenv.sh: line 39: /u01/app/oracle/product/12.2.0.1/dbhome/network/admin/listener.ora: No such file or directory
/scripts/setenv.sh: line 40: /u01/app/oracle/product/12.2.0.1/dbhome/network/admin/listener.ora: No such file or directory
/scripts/setenv.sh: line 41: /u01/app/oracle/product/12.2.0.1/dbhome/network/admin/listener.ora: No such file or directory
/scripts/setenv.sh: line 42: /u01/app/oracle/product/12.2.0.1/dbhome/network/admin/listener.ora: No such file or directory
/scripts/setenv.sh: line 43: /u01/app/oracle/product/12.2.0.1/dbhome/network/admin/listener.ora: No such file or directory
/scripts/setenv.sh: line 44: /u01/app/oracle/product/12.2.0.1/dbhome/network/admin/listener.ora: No such file or directory
chown: cannot access '/u01/app/oracle/product/12.2.0.1/dbhome/network/admin/tnsnames.ora': No such file or directory
chmod: cannot access '/u01/app/oracle/product/12.2.0.1/dbhome/network/admin/tnsnames.ora': No such file or directory
chown: cannot access '/u01/app/oracle/product/12.2.0.1/dbhome/network/admin/listener.ora': No such file or directory
chmod: cannot access '/u01/app/oracle/product/12.2.0.1/dbhome/network/admin/listener.ora': No such file or directory
WARNING: 'UsePAM no' is not supported in Red Hat Enterprise Linux and may cause several problems.
/scripts/entrypoint.sh: line 18: gosu: command not found
/scripts/entrypoint.sh: line 19: gosu: command not found
/scripts/entrypoint.sh: line 22: gosu: command not found
`

If i run docker container. I use linux computer.

**Comment by Dani3lSun** [comment]
Hey @KristjanVall 

it seems so that building the image have already failed. The docker run command shows errors that important parts and paths are missing...
Have you done all installation steps from the readme?
1) Clone or download this repo
2) Download missing software (like Oracle DB, APEX, ORDS, Tomcat, etc...) to the files folder
...
?

**Comment by Dani3lSun** [comment]
The folder / files structur should look like this before building the image:
<img width="416" alt="screen shot 2018-02-08 at 13 29 08" src="https://user-images.githubusercontent.com/698942/35973014-28954456-0cd4-11e8-91a1-5de72a7bc83e.png">

**Comment by KristjanVall** [comment]
Yes i downloaded all in the files
![screen shot 2018-02-08 at 14 30 24](https://user-images.githubusercontent.com/33087780/35973049-a7cac798-0cdc-11e8-822e-5fd5ec0f4378.png)

**Comment by KristjanVall** [comment]
I downloaded the enviroment, not cloned.

**Comment by KristjanVall** [comment]
![screen shot 2018-02-08 at 14 33 06](https://user-images.githubusercontent.com/33087780/35973167-1195d08c-0cdd-11e8-993d-baa4ea2bf2f2.png)

**Comment by Dani3lSun** [comment]
Ok seems good so far, if you disable features in your dockerfile like INSTALL_AOP or INSTALL_LOGGER, etc you don´t have to download it to the files folder...
I never tried building it on linux, but I will test it if it works! Have you tried building it on your mac?

**Comment by KristjanVall** [comment]
I tried in linux and mac also. I disabled some functionality after the error in docker file. Like this

`FROM oraclelinux:7.4

MAINTAINER Daniel Hochleitner <dhochleitner@posteo.de>

# environment variables
ENV INSTALL_APEX=true \
    INSTALL_SQLCL=false \
    INSTALL_LOGGER=false \
    INSTALL_OOSUTILS=false \
    INSTALL_AOP=false \
    DBCA_TOTAL_MEMORY=2048 \
    ORACLE_SID=db12c \
    SERVICE_NAME=db12c \
    ORACLE_BASE=/u01/app/oracle \
    ORACLE_HOME=/u01/app/oracle/product/12.2.0.1/dbhome \
    ORACLE_INVENTORY=/u01/app/oraInventory \
    PASS=oracle \
    ORDS_HOME=/u01/ords \
    JAVA_HOME=/opt/java \
    TOMCAT_HOME=/opt/tomcat \
    APEX_PASS=OrclAPEX12c! \
    APEX_ADDITIONAL_LANG= \
    TIME_ZONE=UTC

# copy all scripts
ADD scripts /scripts/

# copy all files
ADD files /files/

# image setup via shell script to reduce layers and optimize final disk usage
RUN /scripts/install_main.sh

# ssh, database and apex port
EXPOSE 22 1521 8080

# use ${ORACLE_BASE} without product subdirectory as data volume
VOLUME ["${ORACLE_BASE}"]

# entrypoint for database creation, startup and graceful shutdown
ENTRYPOINT ["/scripts/entrypoint.sh"]
`

But still error

**Comment by KristjanVall** [comment]
Also i used exactly this command to run container

docker run -d --name db-apex-dev-container -p 2222:22 -p 8080:8080 -p 1521:1521 -v /dev/shm --tmpfs /dev/shm:rw,nosuid,nodev,exec,size=2g db-apex-dev-image

maby i do not correctly added the volume? like the host side?

**Comment by Dani3lSun** [comment]
So I tested it on a local Ubuntu Server VM (17.10 via VirtualBox) and build seems to run fine...
I just downloaded the master.zip from GitHub and copied all installer files into files directory, after that I ran the docker build...My screen looks different to yours, I do have a lot more output when building:

![docker_build](https://user-images.githubusercontent.com/698942/35975754-1d4e50d8-0cde-11e8-9eb1-8088df240960.gif)

I changed nothing in the dockerfile, no Volume settings and stuff like that...

**Comment by Dani3lSun** [comment]
I had a look at your files again, and maybe it´s because of your gosu file, this file should be named gosu-amd64, but in your environment it is named gosu-amd64.dms
Just download it again here and don´t rename it:
https://github.com/tianon/gosu/releases/download/1.10/gosu-amd64
This file is important, thus it enables the docker container to use SU commands during build...

**Comment by KristjanVall** [comment]
When i download it is already gosu-amd64.dms

**Comment by Dani3lSun** [comment]
confusing, if I download it, it is named gosu-amd64, tested on mac and ubuntu...
Then just rename it to gosu-amd64 and try the build again...
I would do an proper build without cache:
```
docker build --no-cache -t apex-image .
```

**Comment by Dani3lSun** [comment]
Ah seems to be a Safari issue, if I download it via Safari it has indeed this weird .dms file extension...With command line / Firefox / Chrome this doesn´t happen...

**Comment by KristjanVall** [comment]
Yes it did the trick! i removed gosu-amd64.dms the .dms and it works now perfectly!

Thank you 👍

**Comment by Dani3lSun** [comment]
Great that it worked now! Sometimes it´s the small things :)
I just added a new validation mechanism to the build, so it would check if all necessary files are in place:
https://github.com/Dani3lSun/docker-db-apex-dev/commit/104585aa497d77fa9838ec262abffa6b75dfc902
